services:
  server:
    image: vimukthi01/bus-seat-booking-application:server
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=4000

  client:
    image: vimukthi01/bus-seat-booking-application:client
    build: ./client
    ports:
      - "8081:80"
    depends_on:
      - server
